### ISSUE TITLE
题目: 假设高度已知，请写出三栏布局，其中左栏、右栏宽度各为300px，中间自适应。

### ISSUE THREAD

**Issue by maczyt** [maczyt/interview#1]

**Comment by maczyt** [comment]
目前关于CSS布局方法基本为:

1. 浮动 `float`
2. 定位 `position`
3. CSS表格 `displaty: table`
4. 弹性盒子 `flex`
5. 网格布局 `grid`

所以回答该题，可从以上5点切入回答。理解深入，可说出各方法的优缺点。

**Comment by maczyt** [comment]
先定义下公共样式:

``` css
.left, .right {
  width: 300px;
}
.left, .right, .center {
  height: 200px; /* 高度已知条件 */
}
```

**Comment by maczyt** [comment]
## 浮动布局

> html

``` html
<div class="container">
  <div class="left"></div>
  <div class="right"></div>
  <div class="center"></div>
</div>
```
> css

``` css
.left {
  float: left;
}
.right {
  float: right;
}
.center {
  margin-left: 300px;
  margin-right: 300px;
}
```

[点击查看](https://maczyt.github.io/interview/layout/task1.html#float)，我们在进行浏览器宽度大小改变的情况下，可以看到中间会自适应，是我们需要的效果

---

但是由于浏览器和网络爬虫是从上往下解析元素，所以为了网页更友好，应该把`center`元素放到`left`和`right`的上面，这里有两个比较著名的浮动布局解决方案: **圣杯布局**和**双飞翼布局***国产*, 点击了解。

**Comment by maczyt** [comment]
## 定位布局

这个应该没什么好讲的，就是设置父元素为`relative`，然后三栏设置为`absolute`，通过设置不同的`left`和`right`来达到布局效果。

> html
``` html
<article class="left-center-right">
  <div class="left column"></div>
  <div class="right column"></div>
  <div class="center column">
    <h3>当前宽度:
      <code class="code">200px;</code>
    </h3>
    <p>主要内容</p>
  </div>
</article>
```

> css
``` css
.position .left-center-right {
  position: relative;
}

.position .column {
  position: absolute;
  top: 0;
}

.position .left {
  left: 0;
}

.position .right {
  right: 0;
}

.position .center {
  left: 300px;
  right: 300px;
}
```

由于是使用定位，所以三栏元素的顺序是随便的。

**Comment by maczyt** [comment]
## CSS表格布局

> html
``` html
<article class="left-center-right">
  <div class="left column"></div>
  <div class="center column">
    <h3>当前宽度:
      <code class="code">200px;</code>
    </h3>
    <p>主要内容</p>
  </div>
  <div class="right column"></div>
</article>
```
> css
``` css
.table .left-center-right {
  display: table;
  width: 100%;
}

.table .column {
  display: table-cell;
}
```

[点击查看]()

**该知识点待完善**

**Comment by maczyt** [comment]
## 弹性盒子flex布局

> html
``` html
<article class="left-center-right">
  <div class="left column"></div>
  <div class="center column">
    <h3>当前宽度:
      <code class="code">200px;</code>
    </h3>
    <p>主要内容</p>
  </div>
  <div class="right column"></div>
</article>
```
> css
``` css
.flex .left-center-right {
  display: flex;
}

.flex .center {
  flex: 1;
}
```

超级简单便捷，移动端布局利器。

### 参考文章

1. [Flex 布局教程：语法篇](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)
2. [Flex 布局教程：实例篇](http://www.ruanyifeng.com/blog/2015/07/flex-examples.html)

**Comment by maczyt** [comment]
## 网格grid布局

<details>
  <summary>查看代码</summary>

> html
``` html
<article class="left-center-right">
  <div class="left column"></div>
  <div class="center column">
    <h3>当前宽度:
      <code class="code">200px;</code>
    </h3>
    <p>主要内容</p>
  </div>
  <div class="right column"></div>
</article>
```
> css
``` css
.grid .left-center-right {
  display: grid;
  grid-template-columns: 300px auto 300px;
}
```
</details>

grid布局非常强大，只是限于目前兼容性使用较少，不过很值得提前学习使用，也是面试布局方面的一个加分项。

### 参考文章

1. [CSS Grid 网格布局教程](http://www.ruanyifeng.com/blog/2019/03/grid-layout-tutorial.html)
