### ISSUE TITLE
浮动布局三两事

### ISSUE THREAD

**Issue by maczyt** [maczyt/interview#2]
#1 中简单使用了浮动布局。

这里让我们来介绍下浮动布局中两大重要考察点：圣杯&双飞翼。

**Comment by maczyt** [comment]
## 圣杯布局
> [来源文章](https://alistapart.com/article/holygrail/)

### 原理

设置父容器的左右padding，以便空出位置来放脱离文档流的元素。再通过设置`left`和`right`的margin结合定位来移动到具体的padding位置上。

> html
``` html
<article class="left-center-right">
  <div class="center"></div>
  <div class="left"></div>
  <div class="right"></div>
</article>
```

> css
``` css
body {
  min-width: 900px;
}
.left-center-right {
  padding: 0 300px;
}

.shengbei .left,
.shengbei .right,
.shengbei .center {
  float: left;
}

.shengbei .center {
  width: 100%;
}

.shengbei .left {
  margin-left: -100%;
  position: relative;
  right: 300px;
}

.shengbei .right {
  margin-right: -300px;
}
```


**当页面缩放到较小的页面时，可以发现会错位，这是由于没有设置页面最小宽度的原因**

最最最小的宽度计算：`left width + left postion width + right width`

[效果查看](https://maczyt.github.io/interview/layout/task2.html#shengbei)

**Comment by maczyt** [comment]
## 双飞翼布局

### 原理
使用额外元素`extra`包裹`center`, 设置`center`的左右`margin`（或者是`extra`的左右`padding`）来留出位置，设置`left`和`right`元素的`margin`来移动到具体位置，不需要使用定位。

> html
``` html
<article class="left-center-right">
  <div class="extra column">
    <div class="center">
      <h3>当前宽度:
        <code class="code"></code>
      </h3>
      <p>主要内容</p>
    </div>
  </div>
  <div class="left column"></div>
  <div class="right column"></div>
</article>
```

> css

``` css
body { min-width: 600px; }
.sfy .column {
  float: left;
}

.sfy .extra {
  width: 100%;
  height: 100%;
}

.sfy .center {
  margin: 0 300px;
}

.sfy .left {
  margin-left: -100%;
}

.sfy .right {
  margin-left: -300px;
}
```

同样需要设置下最小宽度：left width + right  width

[效果查看](https://maczyt.github.io/interview/layout/task2.html#sfy)
